# Generated by Django 5.0.4 on 2024-05-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertbl',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
