# Generated by Django 5.0.4 on 2024-05-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionapp', '0002_customertbl_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
