# Generated by Django 5.0.4 on 2024-05-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionapp', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
