# Generated by Django 5.0.4 on 2024-05-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionapp', '0004_admin_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertbl',
            name='type',
        ),
    ]
