# Generated by Django 5.0.4 on 2024-05-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionapp', '0005_remove_customertbl_type'),
        ('actionapp', '0006_migrate_users'),
    ]

    operations = [
    ]
